### ISSUE TITLE
Business timesheet field must be changed to a string column AND NOT POINT TO AN EXTERNAL TABLE WITH WORKING HOURS

### ISSUE THREAD

**Issue by ValdasVabolis** [ValdasVabolis/Defense-of-the-Trade-League-Locals-Edition#7]
We save timesheet data in JSON format: "{"day-Monday": "hourFrom": 9, "minuteFrom": 5 ... etc }
This will be saved a string column in the database, and when retrieved converted into actual JSON using JSON.parse

**Comment by EvalVis** [comment]
Resolve this by converting JSON to TimeSheet object.
